### ISSUE TITLE
通过buildSrc统一管理依赖库

### ISSUE THREAD

**Issue by fakeSleeper** [zskingking/Jetpack-WanAndroid#10]
请教一下，你于2020年9月17号添加的“buildSrc”是个什么模块？怎么与“app”模块和“base-library”模块产生联系的，怎么在app和base-library中就能直接调用 buildSrc中的那几个objec类了？我看了半天，没有搞懂，烦请兄弟有空帮忙释疑一下，感谢。 ps：代码写的的确很美观

**Comment by zskingking** [comment]
其实就是kotlin dsl写法，通常gradle是用groovy语言写的，之所以kotlin可以直接引用(即智能提示)是因为它是静态语言，而groovy是动态语言所以不支持直接引用。。。关于什么是buildSrc给你推荐一篇文章，相信能找到你的答案 https://juejin.cn/post/6844904176250519565

**Comment by fakeSleeper** [comment]
谢谢了，正好刚刚领略了kotlin dsl 之美
