### ISSUE TITLE
项目运行不了e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by dd9000901** [zskingking/Jetpack-WanAndroid#12]
e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by zskingking** [comment]
> e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

项目用的是JDK8.0，我搜了下JDK8.0以上可能会报这个错，你可以尝试在gradle将java版本调整下，或者更改下jdk版本

**Comment by zskingking** [comment]
刚又研究了下，as升级到4.2后jdk location默认是11，而本读是jdk 1.8所以冲突了。具体解决方案 https://stackoverflow.com/questions/67410927/java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-after-updating-to-a
