### ISSUE TITLE
关于LiveData状态共享的倒灌问题

### ISSUE THREAD

**Issue by spysoos** [zskingking/Jetpack-WanAndroid#14]
关于LiveData状态共享的倒灌问题
请问 
一个LiveData被多个fragment分享，当前一个fragment收到后退出，再返回，仍然会收到LiveData之前的值，而理想的状态是Fragment只接收到一次，销耗后就不再接受旧值

**Comment by zskingking** [comment]
> 关于LiveData状态共享的倒灌问题
> 请问
> 一个LiveData被多个fragment分享，当前一个fragment收到后退出，再返回，仍然会收到LiveData之前的值，而理想的状态是Fragment只接收到一次，销耗后就不再接受旧值

这种建议就不要共享LiveData了，非要共享推荐KunMinx大佬的 https://github.com/KunMinX/UnPeek-LiveData 。希望能解决你的问题
