### ISSUE TITLE
关于框架的一些疑虑

### ISSUE THREAD

**Issue by x930073498** [zskingking/Jetpack-WanAndroid#15]
谢谢大佬的框架，我在挑选框架的时候看到了大佬的库，感觉很不错。不过其中有一些小疑虑。

1、就是databinding与业务的紧密耦合，导致页面的复用性很差，大佬可有想过用其他方式去实现。
2、我看一个UI组件（fragment，activity）中只能使用一个viewModel与页面的databinding 通过DataBindingConfig绑定，如果一个fragment或者actvity中有多个业务的组合，即可能有多个viewmodel同时作为一个UI单元的数据源时，框架该如何做？

最后再次谢谢大佬的框架。

**Comment by zskingking** [comment]
> 谢谢大佬的框架，我在挑选框架的时候看到了大佬的库，感觉很不错。不过其中有一些小疑虑。
> 
> 1、就是databinding与业务的紧密耦合，导致页面的复用性很差，大佬可有想过用其他方式去实现。
> 2、我看一个UI组件（fragment，activity）中只能使用一个viewModel与页面的databinding 通过DataBindingConfig绑定，如果一个fragment或者actvity中有多个业务的组合，即可能有多个viewmodel同时作为一个UI单元的数据源时，框架该如何做？
> 
> 最后再次谢谢大佬的框架。

这个我觉得可以再细分一点，既然可以用同一套xml说明对应的数据也差不多，可以将ViewModel中根据业务将LiveData/ObservableFiled拆封到不同的Request中，而业务对应的Request存储到ViewModel中，大概代码如下：
 class UserVm :ViewModel(){
        val userRequest = UserRequest()
    }
    
    class UserRequest{
        val userName = ObservableField<String>()
        val passWord = ObservableField<String>()
    }

**Comment by x930073498** [comment]
了解
