### ISSUE TITLE
Adapter item 获取自定义属性

### ISSUE THREAD

**Issue by hunimeizi** [zskingking/Jetpack-WanAndroid#16]
您好，为什么adapter中item布局使用textview自定义属性style="@style/text_2"（?attr/theme_color_2）直接回崩溃掉，不在recycleview里使用就会正常呢

**Comment by zskingking** [comment]
> 您好，为什么adapter中item布局使用textview自定义属性style="@style/text_2"（?attr/theme_color_2）直接回崩溃掉，不在recycleview里使用就会正常呢

这是主题属性，你大概率是给覆盖掉了，查阅一下RecyclerView以及对应的itemLayout有没有设置主题，有的话取消就行了

**Comment by hunimeizi** [comment]
非常感谢，已解决
