### ISSUE TITLE
拉去代码后，运行不了。

### ISSUE THREAD

**Issue by zhf827** [zskingking/Jetpack-WanAndroid#17]
e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

希望楼主多多优化。

**Comment by zskingking** [comment]
> e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> 
> 希望楼主多多优化。

这个错误README.md第一行我提了，贴的链接里有解决方案

**Comment by zhf827** [comment]
是我没看完，我的锅。

**Comment by zskingking** [comment]
> 是我没看完，我的锅。

嗯，能解决就好~~
