### ISSUE TITLE
建议：播放器可以增加通知栏和锁屏事件

### ISSUE THREAD

**Issue by baowenqing** [zskingking/Jetpack-WanAndroid#4]
建议播放器可以增加通知栏和锁屏事件，更加完善；大佬有空的话，帮忙加一下，学习学习O(∩_∩)O

**Comment by zskingking** [comment]
> 建议播放器可以增加通知栏和锁屏事件，更加完善；大佬有空的话，帮忙加一下，学习学习O(∩_∩)O

感谢提出意见。通知栏和锁屏是在计划之内的，只是最近比较忙耽搁了，抽空我会补上的。
