### ISSUE TITLE
自定义颜色引用报错 

### ISSUE THREAD

**Issue by wkboys** [zskingking/Jetpack-WanAndroid#5]
我想把项目重新写一下 然后splash 中  android:background="?attr/main_bg_1" 的颜色引用 报错  Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1}  主题和自定义颜色也复制到新项目了 请问大神是什么原因

**Comment by zskingking** [comment]
> 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因

values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去

**Comment by wkboys** [comment]
> > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> 
> values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去

加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色

**Comment by zskingking** [comment]
> > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > 
> > 
> > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> 
> 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色

跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。

**Comment by wkboys** [comment]
> > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > 
> > > 
> > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > 
> > 
> > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> 
> 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。

我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢

**Comment by zskingking** [comment]
> > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > 
> > > > 
> > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > 
> > > 
> > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > 
> > 
> > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> 
> 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢

我帮你排查了下，应该是app工程里style里面也有个AppTheme主题，项目跑起来把module_main中的AppTheme替换了，所以引用不到主题属性。你把app工程的AppTheme主题属性名改下或者删了应该就好了

**Comment by zskingking** [comment]
> > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > 
> > > > 
> > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > 
> > > 
> > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > 
> > 
> > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> 
> 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢

如果解

**Comment by zskingking** [comment]
> > > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > > 
> > > > > 
> > > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > > 
> > > > 
> > > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > > 
> > > 
> > > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> > 
> > 
> > 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢
> 
> 我帮你排查了下，应该是app工程里style里面也有个AppTheme主题，项目跑起来把module_main中的AppTheme替换了，所以引用不到主题属性。你把app工程的AppTheme主题属性名改下或者删了应该就好了



> > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > 
> > > > 
> > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > 
> > > 
> > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > 
> > 
> > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> 
> 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢

如果问题解决了麻烦告知我下啊，我先把issues close掉

**Comment by zskingking** [comment]
> > > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > > 
> > > > > 
> > > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > > 
> > > > 
> > > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > > 
> > > 
> > > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> > 
> > 
> > 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢
> 
> 我帮你排查了下，应该是app工程里style里面也有个AppTheme主题，项目跑起来把module_main中的AppTheme替换了，所以引用不到主题属性。你把app工程的AppTheme主题名改下或者删了应该就好了

**Comment by zskingking** [comment]
> > > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > > 
> > > > > 
> > > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > > 
> > > > 
> > > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > > 
> > > 
> > > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> > 
> > 
> > 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢
> 
> 我帮你排查了下，应该是app工程里style里面也有个AppTheme主题，项目跑起来把module_main中的AppTheme替换了，所以引用不到主题属性。你把app工程的AppTheme主题属性名改下或者删了应该就好了

上面描述有点问题。是把app工程的AppTheme主题名改下，不是主题属性名。只要保证不冲突即可

**Comment by wkboys** [comment]
> > > > > > > 我想把项目重新写一下 然后splash 中 android:background="?attr/main_bg_1" 的颜色引用 报错 Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301da a=-1} 主题和自定义颜色也复制到新项目了 �请问大神是什么原因
> > > > > > 
> > > > > > 
> > > > > > values下有个attr文件，里面包含自定义属性你加进去了吗。另外Activity也要把当前主题设置进去
> > > > > 
> > > > > 
> > > > > 加上了 点击背景颜色的值可以跳转到attr 中 ，清单文件也设置了主题。查看splash 的xml文件的时候您的项目背景图颜色是黑色 ，我重写的是白色
> > > > 
> > > > 
> > > > 跑起来正常吗？不要以xml为准，xml是可以选择主题预览的。如果跑起来还闪退的话，再排查一下主题是否配错。我的项目是在Activity的super.onCreate()之前动态配的主题，如果你按照要求写了应该不会出现问题的啊。
> > > 
> > > 
> > > 我把代码传到自己的git了 您有时间帮我看一下 地址是 https://github.com/wkboys/Template.git 谢谢
> > 
> > 
> > 我帮你排查了下，应该是app工程里style里面也有个AppTheme主题，项目跑起来把module_main中的AppTheme替换了，所以引用不到主题属性。你把app工程的AppTheme主题属性名改下或者删了应该就好了
> 
> 上面描述有点问题。是把app工程的AppTheme主题名改下，不是主题属性名。只要保证不冲突即可

哈哈 谢谢 问题解决了
