### ISSUE TITLE
build错误

### ISSUE THREAD

**Issue by JumpingError** [zskingking/Jetpack-WanAndroid#7]
一直卡在ERROR: Unknown host 'd29vzk4ow07wi7.cloudfront.net'. You may need to adjust the proxy settings in Gradle  
Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.3.21/kotlin-annotation-processing-gradle-1.3.21.jar'

**Comment by zskingking** [comment]
kapt下载失败，是不是你网有问题？或者你在其他项目加入kapt看是否能运行。不行的话尝试在repositories改变一下镜像地址，可以去百度搜一下

**Comment by JumpingError** [comment]
网络没问题，问题在于buildSrc &nbsp;删除这个是可以下载成功的，有这个文件存在就不行，不知道是不是和studio版本有关系，我的是3.5.2的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zs_kingking"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 上午10:21
收件人: "zskingking/Jetpack-Mvvm"<Jetpack-Mvvm@noreply.github.com&gt;; 
抄送: "11111111"<1336814364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zskingking/Jetpack-Mvvm] build错误 (#7)





 
kapt下载失败，是不是你网有问题？或者你在其他项目加入kapt看是否能运行。不行的话尝试在repositories改变一下镜像地址，可以去百度搜一下

**Comment by zskingking** [comment]
可能是的，我公司家里都是4.x，都没问题，而且我同学那边拉也没问题。不行的话你就把buildSrc给干掉吧，这玩意影响编译速度，我这边也准备干掉了。

**Comment by JumpingError** [comment]
嗯嗯 ，我开了vpn拉下来了，我现在已经把他删除了，已经能正常编译了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zs_kingking"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 上午10:35
收件人: "zskingking/Jetpack-Mvvm"<Jetpack-Mvvm@noreply.github.com&gt;; 
抄送: "11111111"<1336814364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zskingking/Jetpack-Mvvm] build错误 (#7)





 
可能是的，我公司家里都是4.x，都没问题，而且我同学那边拉也没问题。不行的话你就把buildSrc给干掉吧，这玩意影响编译速度，我这边也准备干掉了。
