### ISSUE TITLE
关于navigation请教两个问题！

### ISSUE THREAD

**Issue by PickyQiu** [zskingking/Jetpack-WanAndroid#8]
有两个问题想请教一下：
1，A跳转到B的同时，如何关闭A？
2，A-B-C-D,此时如何在D直接回到A（关闭B和C）？

**Comment by zskingking** [comment]
给你推荐一篇文章，这里应该能找到你要的答案。https://www.jianshu.com/p/8abff4381585

**Comment by PickyQiu** [comment]
> 给你推荐一篇文章，这里应该能找到你要的答案。https://www.jianshu.com/p/8abff4381585

好的  谢谢哈！
